### ISSUE TITLE
Replace `tableRowIndex` with destructure addition

### ISSUE THREAD

**Issue by ecumene** [adam-paul952/dart-scoreboard#6]
https://github.com/adam-paul952/dart-scoreboard/blob/5cadd8347b7d2cc6222dfe6d5ada7c3aee7f613c/src/CreatePlayer.js#L50

```
setTableRows([...tableRows, {playerName: ''}]);
```

**Comment by adam-paul952** [comment]
Completed

**Comment by adam-paul952** [comment]
@ecumene I have this done but I had to pass index as an argrument

`const addNewRow = (index) => {
    setTableRows([...tableRows, {index: index, playerName: ''}]);
  };`
