### ISSUE TITLE
Create more tests for Header

### ISSUE THREAD

**Issue by ecumene** [adam-paul952/dart-scoreboard#70]
Write tests for:
 
 - [x] goBackButton (false)
 - [x] resetButton (false)
 - [x] switchThemeButton (false)
 - [x] outShotButton (false)
 - [x] outShotButton (true)
 - [x] loginDropDown (false)

===
 - [x] Search for anchor tags and make sure they have the correct URLs
 - Edit User
 - Delete User
 - LogOut

===
 - [x] goBackButton (true)
 -   [Check location after goBackButton click](https://v5.reactrouter.com/web/guides/testing/checking-location-in-tests)

===
 - [x] resetButton (true)
 -     resetScoreList (this gets called when you click reset button)

===
 - [x] switchThemeButton (true) 
 -     when clicking the button you should call the themeToggle (from props, not context... refactor)

===
 - [x] loginDropDown (true)
 -      Click the dropdown 
 -      Then click the logout button
 -      Then check that it removes all items from the session storage
```
sessionStorage.setItem('key', 'value');

// Get saved data from sessionStorage
let data = sessionStorage.getItem('key');
expect(data).toBe(undefined)
```

**Comment by adam-paul952** [comment]
Complete
