### ISSUE TITLE
Combine CreatePlayer tests

### ISSUE THREAD

**Issue by ecumene** [adam-paul952/dart-scoreboard#73]
Combine 

https://github.com/adam-paul952/dart-scoreboard/blob/8e27ae03c83daad7b7064f5eba6ae64bcbf0a868/src/screens/__tests__/CreatePlayer.test.js#L34

With 

https://github.com/adam-paul952/dart-scoreboard/blob/8e27ae03c83daad7b7064f5eba6ae64bcbf0a868/src/screens/__tests__/CreatePlayer.test.js#L67

**Comment by adam-paul952** [comment]
Complete
