### ISSUE TITLE
Remove `getAllByRole` replace with `getByText` via `test.each`

### ISSUE THREAD

**Issue by ecumene** [adam-paul952/dart-scoreboard#75]
https://github.com/adam-paul952/dart-scoreboard/blob/8e27ae03c83daad7b7064f5eba6ae64bcbf0a868/src/screens/createGame/__tests__/EliminationSetUp.test.js#L39

 - [x] Replace with getByText
 - [x] The one below too!

**Comment by ecumene** [comment]
This too!

https://github.com/adam-paul952/dart-scoreboard/blob/8e27ae03c83daad7b7064f5eba6ae64bcbf0a868/src/screens/createGame/__tests__/X01SetUp.test.js#L37

**Comment by adam-paul952** [comment]
Complete
