### ISSUE TITLE
Lowercase routes

### ISSUE THREAD

**Issue by ecumene** [adam-paul952/dart-scoreboard#8]
https://github.com/adam-paul952/dart-scoreboard/blob/5cadd8347b7d2cc6222dfe6d5ada7c3aee7f613c/src/Routes.js#L20

**Comment by ecumene** [comment]
Ex: Replace create game with `/game/create`

`/game/baseball`
`/game/cricket`...

**Comment by adam-paul952** [comment]
Complete
